/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddButtonEdge: typeof import('./src/components/vflow/AddButtonEdge.vue')['default']
    BaseNode: typeof import('./src/components/vflow/BaseNode.vue')['default']
    ColorSelectorNode: typeof import('./src/components/vflow/ColorSelectorNode.vue')['default']
    copy: typeof import('./src/components/flow/FlowVersionTable copy.vue')['default']
    CustomEdge: typeof import('./src/components/vflow/CustomEdge.vue')['default']
    EdgeAddBtn: typeof import('./src/components/vflow/EdgeAddBtn.vue')['default']
    EmptyNode: typeof import('./src/components/vflow/EmptyNode.vue')['default']
    EndNode: typeof import('./src/components/vflow/EndNode.vue')['default']
    FlowTaskTable: typeof import('./src/components/flow/FlowTaskTable.vue')['default']
    FlowVersionTable: typeof import('./src/components/flow/FlowVersionTable.vue')['default']
    MView: typeof import('./src/components/MView.vue')['default']
    Node: typeof import('./src/components/vflow/Node.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartNode: typeof import('./src/components/vflow/StartNode.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCol: typeof import('tdesign-vue-next')['Col']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    THeader: typeof import('tdesign-vue-next')['Header']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInputAdornment: typeof import('tdesign-vue-next')['InputAdornment']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLink: typeof import('tdesign-vue-next')['Link']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TOption: typeof import('tdesign-vue-next')['Option']
    TRow: typeof import('tdesign-vue-next')['Row']
    TSapce: typeof import('tdesign-vue-next')['Sapce']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    VueFlowView: typeof import('./src/components/vflow/VueFlowView.vue')['default']
  }
}
